backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: "Landing Pages"
    name: "landingPages"
    folder: "/content/landingPages"
    create: true
    fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: "Frames"
          name: "frames"
          widget: list
          types:
            - label: "Standard"
              name: "standard"
              widget: list
              fields:
                - { label: "Header", name: "header", widget: "string"}
                - { label: "Subtitle", name: "subtitle", widget: "string"}
                - { label: "Button", name: "button", widget: "string"}
                - { label: "Description", name: "description", widget: "text"}
                - { label: "Image", name: "img", widget: "image", optional: true}
                - label: "text-boxes"
                  name: "textbox"
                  widget: list
                  optional: true
                  fields:
                    - { label: "Title", name: "title", widget: "string"}
                    - { label: "Text", name: "text", widget: "text"}
  - label: "Projects"
    name: "projects"
    folder: "/content/projects"
    create: true
    fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "string"}
        - { label: "Image", name: "img", widget: "image", optional: true}
  
  - name: "pages"
    label: "Pages"
    files:
    - label: "Nav"
      name: "nav"
      file: "content/nav.md"
      fields:
        - { label: "Name", name: "name", widget: "string"}
        - { label: "Path", name: "path", widget: "string" }
    - label: "List of Projects"
      name: "listProjects"
      file: "content/nav.md"
      fields:
        - { label: "Name", name: "name", widget: "string"}
        - { label: "Path", name: "path", widget: "string" }




          

    

