backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: "Page"
    name: "page"
    folder: "content"
    create: true
    fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: "Frames"
          name: "frames"
          widget: list
          fields:
            - { label: "Header", name: "header", widget: "string"}
            - { label: "Subtitle", name: "subtitle", widget: "string"}
            - { label: "Button", name: "button", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Image", name: "img", widget: "image"}
          

    

