backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: "Frames"
          name: "frames"
          widget: list
          fields:
            - { label: "Header", name: "header", widget: "string"}
            - { label: "Subtitle", name: "subtitle", widget: "string"}
            - { label: "Button", name: "button", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Image", name: "img", widget: "image"}
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: "Frames"
          name: "frames"
          widget: list
          fields:
            - { label: "Header", name: "header", widget: "string"}
            - { label: "Subtitle", name: "subtitle", widget: "string"}
            - { label: "Button", name: "button", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Image", name: "img", widget: "image"}

    

